<a href="https://colab.research.google.com/github/ajak2k/Neural-Networks/blob/master/Kohonen_Self_Organizing_Maps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Initialization of Parameters

In [8]:
import numpy as np
inputs = np.array([[1, 1, 1, -1], [-1, -1, -1, 1], [1, -1, -1, -1], [-1, -1, 1, 1]])

#Setting the initial weights
#weights = np.array([[0.2, 0.6, .05,0.9], [0.8, 0.4, 0.7, 0.3]])
weights = np.array([0.2, 0.8, 0.6, 0.4, 0.5, 0.7, 0.9, 0.3])
weights = weights.reshape((4, 2)) 
weights = weights.transpose()

a = 0.9 #Learning Rate

m = 4 #Number of input neurons
n = 2 #Number of clusters

epoch = 1000

[[0.2  0.6  0.05 0.9 ]
 [0.8  0.4  0.7  0.3 ]]


Training

In [0]:
for i in range(epoch):
  for j in range(m):
    ed1 = ( ( inputs[j] - weights[0] ) ** 2 ).sum()
    ed2 = ( ( inputs[j] - weights[1] ) ** 2 ).sum()
    if( ed1 < ed2 ):
      weights[0] = weights[0] + a * (inputs[j] - weights[0])
    else:
      weights[1] = weights[1] + a * (inputs[j] - weights[1])
  a = a * 0.5
      

Testing and Validation

In [3]:
print(weights.transpose())
for j in range(m):
    ed1 = ( ( inputs[j] - weights[0] ) ** 2 ).sum()
    ed2 = ( ( inputs[j] - weights[1] ) ** 2 ).sum()
    if( ed1 < ed2 ):
     print('For this input')
     print(inputs[j])
     print('belong to cluster 1')
    else:
     print('For this input')
     print(inputs[j])
     print('belong to cluster 2')




[[-0.97938355  0.99772445]
 [-0.99981796 -0.01480825]
 [ 0.21295147 -0.01139493]
 [ 0.9795087  -0.98520895]]
For this input
[ 1  1  1 -1]
belong to cluster 2
For this input
[-1 -1 -1  1]
belong to cluster 1
For this input
[ 1 -1 -1 -1]
belong to cluster 2
For this input
[-1 -1  1  1]
belong to cluster 1
